### PR TITLE
Changed user property 'followees' to 'following' to match backend naming conventions

### PR DESCRIPTION
**Pull request by tdunbar123**

### CODE REVIEW

**Review by escalonn — CHANGES_REQUESTED** [review]
fix

**Review by escalonn — APPROVED** [review]
for "property binding"? you mean, to match what the backend is sending/expecting, right?

**Comment by tdunbar123** [comment]
^Yes

**Comment by escalonn** [comment]
@tdunbar123 rename the PR so it's clearer

**Comment by tdunbar123** [comment]
@escalonn how's this?

**Pull request merged**
