### PR TITLE
Ft newsfeed

### PR DESCRIPTION
**Pull request by dipoosinubi**

### CODE REVIEW

**Comment by yetanothersegfault** [comment]
This is huge because it combines another branch that had not been merged to a us- story yet.

**Comment by yetanothersegfault** [comment]
This is apparently 3 in one. sorry for the huge PR

**Review by escalonn — COMMENTED** [review]
target branch is not up to date with main.
this PR also includes changes from other PRs. this is obviously a problem, fragments code review, causes unneeded merge conflicts. it's your responsibility to avoid all possible bad results of that, like effectively reverting good changes made on another PR's version of some of this code.

the production url is wrong. code review of the rest of this was very cursory.

**Comment by yetanothersegfault** [comment]
Making new branch with new PR. Closing

**Pull request closed without merging**
